version: "3.8"

services:
  frontend:
    image: altfrontend
    container_name: frontend
    ports:
      - "3000:80"  
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    image: altbackend
    container_name: backend
    ports:
      - "7070:7070"  
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
    networks:
      - app_network

  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
