version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./Frontend  # Path to the frontend directory
      dockerfile: Dockerfile  # Ensure Dockerfile is inside the frontend directory
    ports:
      - "3000:80"  
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    container_name: backend
    build:
      context: ./Backend  # Path to the backend directory
      dockerfile: Dockerfile  # Ensure Dockerfile is inside the backend directory
    ports:
      - "7070:7070"  
    networks:
      - app_network
    env_file:
      - .env  # Load environment variables from .env file
    command: [ "sh", "-c", "npx prisma migrate deploy && node server.js" ]

networks:
  app_network:
